//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BlackHoleServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlackHoleServer.IBlackHole")]
    public interface IBlackHole {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/PullStarship", ReplyAction="http://tempuri.org/IBlackHole/PullStarshipResponse")]
        Lib.Starship PullStarship(Lib.Starship ship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/PullStarship", ReplyAction="http://tempuri.org/IBlackHole/PullStarshipResponse")]
        System.Threading.Tasks.Task<Lib.Starship> PullStarshipAsync(Lib.Starship ship);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackHoleChannel : Client.BlackHoleServer.IBlackHole, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackHoleClient : System.ServiceModel.ClientBase<Client.BlackHoleServer.IBlackHole>, Client.BlackHoleServer.IBlackHole {
        
        public BlackHoleClient() {
        }
        
        public BlackHoleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackHoleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackHoleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackHoleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lib.Starship PullStarship(Lib.Starship ship) {
            return base.Channel.PullStarship(ship);
        }
        
        public System.Threading.Tasks.Task<Lib.Starship> PullStarshipAsync(Lib.Starship ship) {
            return base.Channel.PullStarshipAsync(ship);
        }
    }
}
